/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import javax.swing.*;
import javax.swing.border.*;
import static classes.OTP.otp;
import static classes.hashifier.gethash;
import static classes.quotes.quote;
import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;


/**
 *
 * @author root
 */
public class Login_signup extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Login_signup() {
        initComponents();
 
    }
 int a,b;
 String pin=(otp());
 String mailer=null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root = new javax.swing.JPanel();
        holder = new javax.swing.JPanel();
        jPanelSlider1 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        login = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel19 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Signup = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel21 = new javax.swing.JLabel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        forgetpass = new javax.swing.JPanel();
        jPanelSlider2 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        jPanel6 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        jLabel24 = new javax.swing.JLabel();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        kGradientPanel7 = new keeptoo.KGradientPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        kGradientPanel9 = new keeptoo.KGradientPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jPasswordField4 = new javax.swing.JPasswordField();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        loader = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        root.setOpaque(false);
        root.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                rootMouseDragged(evt);
            }
        });
        root.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rootMousePressed(evt);
            }
        });
        root.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        holder.setBackground(new java.awt.Color(255, 255, 255));
        holder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSlider1.setBorder(null);

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel2.setText("Email ");
        login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel3.setText("Password");
        login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Forgotten Password?");
        jLabel4.setToolTipText("Change Password Here");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });
        login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 170, 30));

        jTextField1.setForeground(new java.awt.Color(135, 135, 135));
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField1MousePressed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        login.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 290, 30));

        jPasswordField1.setFont(new java.awt.Font("DejaVu Sans", 1, 15)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(135, 135, 135));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jPasswordField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordField1MousePressed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        login.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 290, 30));

        jLabel5.setForeground(new java.awt.Color(0, 204, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("or");
        login.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 400, 20, -1));

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 0, 9)); // NOI18N
        login.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 130, 20));

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 0, 9)); // NOI18N
        login.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 130, 20));

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 0, 9)); // NOI18N
        login.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 110, 20));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 204, 102));
        kGradientPanel1.setkGradientFocus(100);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("LOGIN");
        jLabel19.setToolTipText("LOGIN");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19MouseExited(evt);
            }
        });
        kGradientPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        login.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 100, 30));

        kGradientPanel2.setkEndColor(new java.awt.Color(0, 204, 102));
        kGradientPanel2.setkGradientFocus(100);
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("SIGNUP");
        jLabel20.setToolTipText("Crete New Account");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel20MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel20MouseEntered(evt);
            }
        });
        kGradientPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        login.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 70, 30));

        jLabel40.setFont(new java.awt.Font("DejaVu Sans", 1, 25)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 204, 153));
        jLabel40.setText("LOGIN");
        login.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select User Type", "Admin", "Accountant", "Other" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox1MousePressed(evt);
            }
        });
        login.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 290, 20));

        jPanelSlider1.add(login, "card2");

        Signup.setBackground(new java.awt.Color(255, 255, 255));
        Signup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 0, 13)); // NOI18N
        jLabel9.setText("User Name");
        Signup.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 100, -1));

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 0, 13)); // NOI18N
        jLabel10.setText("Email Address");
        Signup.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 120, -1));

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 0, 13)); // NOI18N
        jLabel11.setText("Mobile Number");
        Signup.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 130, -1));

        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 0, 13)); // NOI18N
        jLabel12.setText("Password");
        Signup.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 90, -1));

        jComboBox2.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select User Type", "Admin", "Accountant", "Other" }));
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox2MousePressed(evt);
            }
        });
        Signup.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 280, 20));

        jTextField2.setForeground(new java.awt.Color(143, 143, 143));
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField2MousePressed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        Signup.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 200, 20));

        jTextField3.setForeground(new java.awt.Color(143, 143, 143));
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField3MousePressed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        Signup.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 200, 20));

        jTextField4.setForeground(new java.awt.Color(143, 143, 143));
        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField4MousePressed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        Signup.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 250, 30));

        jTextField5.setForeground(new java.awt.Color(143, 143, 143));
        jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField5MousePressed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        Signup.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 250, 30));

        jPasswordField2.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(143, 143, 143));
        jPasswordField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jPasswordField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordField2MousePressed(evt);
            }
        });
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyReleased(evt);
            }
        });
        Signup.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 250, 30));

        jLabel14.setFont(new java.awt.Font("DejaVu Sans", 0, 9)); // NOI18N
        Signup.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 160, 20));

        jLabel15.setFont(new java.awt.Font("DejaVu Sans", 0, 9)); // NOI18N
        Signup.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 150, 20));

        jLabel16.setFont(new java.awt.Font("DejaVu Sans", 0, 9)); // NOI18N
        Signup.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 160, 20));

        jLabel17.setFont(new java.awt.Font("DejaVu Sans", 0, 9)); // NOI18N
        Signup.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 150, 20));

        jLabel18.setFont(new java.awt.Font("DejaVu Sans", 0, 9)); // NOI18N
        Signup.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 150, 30));

        kGradientPanel3.setkEndColor(new java.awt.Color(0, 204, 102));
        kGradientPanel3.setkGradientFocus(100);
        kGradientPanel3.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("CREATE ACCOUNT");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21MouseExited(evt);
            }
        });
        kGradientPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        Signup.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 150, -1));

        kGradientPanel4.setkEndColor(new java.awt.Color(0, 204, 102));
        kGradientPanel4.setkGradientFocus(100);
        kGradientPanel4.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("LOGIN");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel22MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel22MouseEntered(evt);
            }
        });
        kGradientPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        Signup.add(kGradientPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 80, 30));

        jLabel34.setForeground(new java.awt.Color(0, 255, 102));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("or");
        Signup.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, -1, -1));

        jLabel39.setFont(new java.awt.Font("DejaVu Sans", 1, 25)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 204, 153));
        jLabel39.setText("SIGNUP");
        Signup.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 110, -1));

        jPanelSlider1.add(Signup, "card3");

        forgetpass.setBackground(new java.awt.Color(255, 255, 255));
        forgetpass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSlider2.setBorder(null);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField6.setFont(new java.awt.Font("DejaVu Sans", 0, 13)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        jTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField6MousePressed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });
        jPanel6.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 330, 30));

        kGradientPanel5.setkEndColor(new java.awt.Color(0, 204, 102));
        kGradientPanel5.setkGradientFocus(100);
        kGradientPanel5.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("GET OTP");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel24MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel24MouseEntered(evt);
            }
        });
        kGradientPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        jPanel6.add(kGradientPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 110, 30));

        kGradientPanel6.setkEndColor(new java.awt.Color(0, 204, 102));
        kGradientPanel6.setkGradientFocus(100);
        kGradientPanel6.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Go To Login");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel25MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel25MouseEntered(evt);
            }
        });
        kGradientPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        jPanel6.add(kGradientPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 90, 30));

        jLabel23.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jLabel23.setText("Enter Registered Email To Get OTP");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel26.setForeground(new java.awt.Color(0, 204, 153));
        jLabel26.setText("or");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, 20));

        jLabel27.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 100, 20));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icos/image4766.png"))); // NOI18N
        jPanel6.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 90, 60));

        jPanelSlider2.add(jPanel6, "card2");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField7.setFont(new java.awt.Font("DejaVu Sans", 0, 13)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        jTextField7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField7MousePressed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyReleased(evt);
            }
        });
        jPanel7.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 330, 30));

        kGradientPanel7.setkEndColor(new java.awt.Color(0, 204, 102));
        kGradientPanel7.setkGradientFocus(100);
        kGradientPanel7.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Varify OTP");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel28MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel28MouseEntered(evt);
            }
        });
        kGradientPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        jPanel7.add(kGradientPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 110, 30));

        jLabel30.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        jLabel30.setText("Enter OTP To Varify");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 110, 20));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icos/image4755.png"))); // NOI18N
        jPanel7.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 90, 60));

        jPanelSlider2.add(jPanel7, "card2");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel9.setkEndColor(new java.awt.Color(0, 204, 102));
        kGradientPanel9.setkGradientFocus(100);
        kGradientPanel9.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Change Password");
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel33MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel33MouseEntered(evt);
            }
        });
        kGradientPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        jPanel8.add(kGradientPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 130, 30));

        jLabel35.setFont(new java.awt.Font("DejaVu Sans", 0, 13)); // NOI18N
        jLabel35.setText("Retype New Password");
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel8.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 100, 20));

        jLabel36.setFont(new java.awt.Font("DejaVu Sans", 0, 13)); // NOI18N
        jLabel36.setText("New Password");
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jPasswordField3.setFont(new java.awt.Font("DejaVu Sans", 1, 15)); // NOI18N
        jPasswordField3.setForeground(new java.awt.Color(135, 135, 135));
        jPasswordField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jPasswordField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordField3MousePressed(evt);
            }
        });
        jPasswordField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField3KeyReleased(evt);
            }
        });
        jPanel8.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 260, 30));

        jPasswordField4.setFont(new java.awt.Font("DejaVu Sans", 1, 15)); // NOI18N
        jPasswordField4.setForeground(new java.awt.Color(135, 135, 135));
        jPasswordField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jPasswordField4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordField4MousePressed(evt);
            }
        });
        jPasswordField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField4KeyReleased(evt);
            }
        });
        jPanel8.add(jPasswordField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 260, 30));

        jLabel29.setFont(new java.awt.Font("DejaVu Sans", 0, 9)); // NOI18N
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 160, 20));

        jLabel31.setFont(new java.awt.Font("DejaVu Sans", 0, 9)); // NOI18N
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 150, 20));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icos/password.png"))); // NOI18N
        jPanel8.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 70, 70));

        jPanelSlider2.add(jPanel8, "card2");

        forgetpass.add(jPanelSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 420, 290));

        jPanelSlider1.add(forgetpass, "card4");

        loader.setBackground(new java.awt.Color(255, 255, 255));
        loader.setPreferredSize(new java.awt.Dimension(560, 420));
        loader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icos/output_B3y1Lp.gif"))); // NOI18N
        loader.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 340, 150));

        jLabel38.setFont(new java.awt.Font("AvenueX", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 153, 153));
        loader.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 380, 120));

        jLabel44.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(153, 153, 153));
        jLabel44.setText("Please wait while we loading.......");
        loader.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("LOADING....");
        loader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jPanelSlider1.add(loader, "card3");

        holder.add(jPanelSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 480));

        root.add(holder, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 590, 480));

        getContentPane().add(root);
        root.setBounds(0, 0, 992, 630);

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icos/ui2.png"))); // NOI18N
        getContentPane().add(img);
        img.setBounds(0, 0, 992, 630);

        setSize(new java.awt.Dimension(990, 629));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rootMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rootMousePressed
a=evt.getX();
b=evt.getY();        // TODO add your handling code here:
    }//GEN-LAST:event_rootMousePressed

    private void rootMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rootMouseDragged
int X=evt.getXOnScreen();
int Y=evt.getYOnScreen();

this.setLocation(X-a,Y-b);        // TODO add your handling code here:
    }//GEN-LAST:event_rootMouseDragged

    private void jPasswordField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField4KeyReleased
        jLabel29.setText("");
    }//GEN-LAST:event_jPasswordField4KeyReleased

    private void jPasswordField4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField4MousePressed
        jPasswordField4.setText("");
    }//GEN-LAST:event_jPasswordField4MousePressed

    private void jPasswordField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField3KeyReleased
        jLabel31.setText("");
    }//GEN-LAST:event_jPasswordField3KeyReleased

    private void jPasswordField3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField3MousePressed
        jPasswordField3.setText("");
    }//GEN-LAST:event_jPasswordField3MousePressed

    private void jLabel33MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseEntered
        Border border = BorderFactory.createLineBorder(Color.WHITE,2);
        jLabel33.setBorder(border);
        jLabel33.setFont(new Font("DejaVu Sans", Font.BOLD, 9));
    }//GEN-LAST:event_jLabel33MouseEntered

    private void jLabel33MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseExited
        jLabel33.setBorder(null);
        jLabel33.setFont(new Font("DejaVu Sans", Font.BOLD, 11));
    }//GEN-LAST:event_jLabel33MouseExited

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        Connection conn=null;
        PreparedStatement pstmt=null;

        String np= jPasswordField3.getText();
        String nph=(gethash(np.getBytes(),"MD5"));
        String rnp= jPasswordField4.getText();
        String nhp=(gethash(rnp.getBytes(),"MD5"));
        String emailn=mailer;
        String emailhashn=(gethash(emailn.getBytes(),"MD5"));
        if(np.equals("")&&rnp.equals(""))

        {jLabel31.setText("Enter New Pass");
            jLabel31.setForeground(Color.red);
            jLabel29.setText("ReEnter New Pass");
            jLabel29.setForeground(Color.red);}
        else
        if(np.equals("")){jLabel31.setText("Enter New Pass");
            jLabel31.setForeground(Color.red);
        }
        else
        if(rnp.equals("")){jLabel29.setText("Enter New Pass");
            jLabel29.setForeground(Color.red);}
        else
        if(nph.equals(nhp)){

            try{
                Class.forName("com.mysql.jdbc.Driver");
                conn=DriverManager.getConnection("jdbc:mysql:///Student_management_System","root","root");
                pstmt=conn.prepareStatement("select email from logged_user where email=?");
                pstmt.setString(1,emailhashn);
                ResultSet rs=pstmt.executeQuery();

                while(rs.next()){

                    if(emailhashn.equals(rs.getString("email"))){
                        pstmt=conn.prepareStatement("UPDATE logged_user SET pass=(?) where email=(?)");

                        pstmt.setString(1,nhp);
                        pstmt.setString(2,emailhashn);

                        int i=pstmt.executeUpdate();

                        if(i>0){JOptionPane.showMessageDialog(null,"<html>Password Changed."
                            + "<br><br>Please Login With changed Password<html>");

                        jPasswordField3.setText("");
                        jPasswordField4.setText("");
                        jLabel31.setText("");
                        jLabel29.setText("");
                        jPanelSlider2.nextPanel(6,jPanel6,jPanelSlider2.left);
                        jPanelSlider1.nextPanel(6,login,jPanelSlider1.left);

                    }
                    else{  JOptionPane.showMessageDialog(null,"Password Doesn't changed");}

                }
                else{
                    JOptionPane.showMessageDialog(null,"Password Doesn't changed");
                }}

            }catch(Exception e){JOptionPane.showMessageDialog(null,e);}}

            else{   JOptionPane.showMessageDialog(null,"Password Doesn't matched");}

    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel28MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseEntered
        Border border = BorderFactory.createLineBorder(Color.WHITE,2);
        jLabel28.setBorder(border);
        jLabel28.setFont(new Font("DejaVu Sans", Font.BOLD, 9));
    }//GEN-LAST:event_jLabel28MouseEntered

    private void jLabel28MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseExited
        jLabel28.setBorder(null);
        jLabel28.setFont(new Font("DejaVu Sans", Font.BOLD, 11));
    }//GEN-LAST:event_jLabel28MouseExited

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked

        String gpin=jTextField7.getText();
        if(gpin.equals("")){jLabel32.setText("Enter OTP");
            jLabel32.setForeground(Color.red);}else{
            if(pin.equals(gpin))
            {
                JOptionPane.showMessageDialog(null,"OTP matched. Change Your Password");
                jPanelSlider2.nextPanel(6,jPanel8,jPanelSlider2.right);
                jTextField7.setText("");
            }
            else{JOptionPane.showMessageDialog(null,"OTP doesn't matched");
                jPanelSlider2.nextPanel(6,jPanel6,jPanelSlider2.left);
                jPanelSlider1.nextPanel(6,login,jPanelSlider1.right);
                jTextField7.setText(""); }}

    }//GEN-LAST:event_jLabel28MouseClicked

    private void jTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased
        jLabel32.setText("");
    }//GEN-LAST:event_jTextField7KeyReleased

    private void jTextField7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MousePressed
        jTextField7.setText("");
    }//GEN-LAST:event_jTextField7MousePressed

    private void jLabel25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseEntered
        Border border = BorderFactory.createLineBorder(Color.WHITE,2);
        jLabel25.setBorder(border);
        jLabel25.setFont(new Font("DejaVu Sans", Font.BOLD, 9));
    }//GEN-LAST:event_jLabel25MouseEntered

    private void jLabel25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseExited
        jLabel25.setBorder(null);
        jLabel25.setFont(new Font("DejaVu Sans", Font.BOLD, 11));
    }//GEN-LAST:event_jLabel25MouseExited

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        jTextField1.setText("");

        jPasswordField1.setText("");
        jComboBox1.setSelectedIndex(0);
        jLabel27.setText("");
        jPanelSlider1.nextPanel(6,login,jPanelSlider1.right);
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseEntered
        Border border = BorderFactory.createLineBorder(Color.WHITE,2);
        jLabel24.setBorder(border);
        jLabel24.setFont(new Font("DejaVu Sans", Font.BOLD, 9));
    }//GEN-LAST:event_jLabel24MouseEntered

    private void jLabel24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseExited
        jLabel24.setBorder(null);
        jLabel24.setFont(new Font("DejaVu Sans", Font.BOLD, 11));
    }//GEN-LAST:event_jLabel24MouseExited

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        Connection conn=null;
        PreparedStatement pstmt=null;

        mailer=jTextField6.getText();
        String emailhas=(gethash(mailer.getBytes(),"MD5"));

        if(mailer.equals("")){jLabel27.setText("Enter Email");
            jLabel27.setForeground(Color.red);
        }

        else{

            try{
                Class.forName("com.mysql.jdbc.Driver");
                conn=DriverManager.getConnection("jdbc:mysql:///Student_management_System","root","root");
                pstmt=conn.prepareStatement("select email from logged_user where email=?");
                pstmt.setString(1,emailhas);
                ResultSet rs=pstmt.executeQuery();

                while(rs.next()){

                    if(emailhas.equals(rs.getString("email"))){
                        JOptionPane.showMessageDialog(null,"<html>Make Sure Your Are Connected To Internet."
                            + "<br> Otherwise You'll get Error.</html>");
                        JOptionPane.showMessageDialog(null,"<html>We will sending OTP to"+" :<br> "+mailer+
                            "."+" <br><br> "+"Please Check Your Email For OTP.<br><br>"
                            + ""+"Please Wait For a While to get OTP.</html>");

                        try{
                            String host ="smtp.gmail.com" ;
                            String user = "adarsh.pr.dev@gmail.com";
                            String pass = "r00t@darsh";
                            String to = mailer;
                            String from = "adarsh.pr.dev@gmail.com";
                            String subject = "This is OTP to change your password for Student Management System Account.";
                            String messageText = ("Your OTP Is : "+" "+ pin);
                            boolean sessionDebug = false;

                            Properties props = System.getProperties();

                            props.put("mail.smtp.starttls.enable", "true");
                            props.put("mail.smtp.host", host);
                            props.put("mail.smtp.port", "587");
                            props.put("mail.smtp.auth", "true");
                            props.put("mail.smtp.starttls.required", "true");

                            java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
                            Session mailSession = Session.getDefaultInstance(props, null);
                            mailSession.setDebug(sessionDebug);
                            Message msg = new MimeMessage(mailSession);
                            msg.setFrom(new InternetAddress(from));
                            InternetAddress[] address = {new InternetAddress(to)};
                            msg.setRecipients(Message.RecipientType.TO, address);
                            msg.setSubject(subject); msg.setSentDate(new java.util.Date());
                            msg.setText(messageText);

                            Transport transport=mailSession.getTransport("smtp");
                            transport.connect(host, user, pass);
                            transport.sendMessage(msg, msg.getAllRecipients());
                            transport.close();
                            JOptionPane.showMessageDialog(null,"OTP send successfully.");
                            jPanelSlider2.nextPanel(6,jPanel7,jPanelSlider2.right);
                            jTextField6.setText("");
                        }catch(Exception ex)
                        {
                            JOptionPane.showMessageDialog(null,ex);
                        }

                    }}

                }catch(Exception e){JOptionPane.showMessageDialog(null,e);}}

    }//GEN-LAST:event_jLabel24MouseClicked

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        jLabel27.setText("");
    }//GEN-LAST:event_jTextField6KeyReleased

    private void jTextField6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MousePressed
        jTextField6.setText("");
    }//GEN-LAST:event_jTextField6MousePressed

    private void jLabel22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseEntered
        Border border = BorderFactory.createLineBorder(Color.WHITE,2);
        jLabel22.setBorder(border);
        jLabel22.setFont(new Font("DejaVu Sans", Font.BOLD, 9));
    }//GEN-LAST:event_jLabel22MouseEntered

    private void jLabel22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseExited
        jLabel22.setBorder(null);
        jLabel22.setFont(new Font("DejaVu Sans", Font.BOLD, 11));
    }//GEN-LAST:event_jLabel22MouseExited

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        jLabel6.setText("");
        jLabel7.setText("");
        jLabel8.setText("");

        jTextField2.setText("");
        jTextField3.setText("");
        jTextField1.setText("");
        jPasswordField1.setText("");
        jComboBox1.setSelectedIndex(0);
        jPanelSlider1.nextPanel(6,login,jPanelSlider1.right);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseExited
        jLabel21.setBorder(null);
        jLabel21.setFont(new Font("DejaVu Sans", Font.BOLD, 13));
    }//GEN-LAST:event_jLabel21MouseExited

    private void jLabel21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseEntered
        Border border = BorderFactory.createLineBorder(Color.WHITE,2);
        jLabel21.setBorder(border);
        jLabel21.setFont(new Font("DejaVu Sans", Font.BOLD, 11));
    }//GEN-LAST:event_jLabel21MouseEntered

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        Connection conn=null;
        PreparedStatement pstmt=null;

        String fname=jTextField2.getText();
        String sname=jTextField3.getText();
        String pass=jPasswordField2.getText();
        String passhash=(gethash(pass.getBytes(),"MD5"));
        String email=jTextField4.getText();
        String emailhash=(gethash(email.getBytes(),"MD5"));
        String mob=jTextField5.getText();
        String mobhash=(gethash(mob.getBytes(),"MD5"));
        String utype=(String)jComboBox2.getSelectedItem();

        if(jTextField2.getText().trim().isEmpty() && jTextField3.getText().trim().isEmpty()
            && jTextField4.getText().trim().isEmpty() && jTextField5.getText().trim().isEmpty()
            && jPasswordField2.getText().trim().isEmpty())
        {
            jLabel14.setText("Enter UserName");
            jLabel14.setText("Enter UserName");
            jLabel14.setForeground(Color.red);
            jLabel17.setText("Enter Password");
            jLabel17.setForeground(Color.red);
            jLabel15.setText("Enter Email");
            jLabel15.setForeground(Color.red);
            jLabel16.setText("Enter Mobile Number");
            jLabel16.setForeground(Color.red);
            jLabel18.setText("Select Authority");
            jLabel18.setForeground(Color.red);

        }

        else
        if(jTextField2.getText().trim().isEmpty())
        {
            jLabel14.setText("Enter UserName");}

        else
        if(jTextField3.getText().trim().isEmpty())

        {
            jLabel14.setText("Enter UserName");
            jLabel14.setForeground(Color.red);}

        else
        if(jPasswordField2.getText().trim().isEmpty()){

            jLabel17.setText("Enter Password");
            jLabel17.setForeground(Color.red);
        }
        else
        if(jTextField4.getText().trim().isEmpty())
        { jLabel15.setText("Enter Email");
            jLabel15.setForeground(Color.red);}
        else
        if(jTextField5.getText().trim().isEmpty())
        { jLabel16.setText("Enter Mobile Number");
            jLabel16.setForeground(Color.red);}
        else
        if(utype.equals("Select User Type"))
        {jLabel18.setText("Select Authority");
            jLabel18.setForeground(Color.red);}
        else{

            try{

                Class.forName("com.mysql.jdbc.Driver");
                conn=DriverManager.getConnection("jdbc:mysql:///student_management_system","root","root");
                pstmt=conn.prepareStatement("insert into logged_user values (?,?,?,?,?,?)");

                pstmt.setString(1,fname);
                pstmt.setString(2,sname);
                pstmt.setString(3,emailhash);
                pstmt.setString(4,mobhash);
                pstmt.setString(5,passhash);
                pstmt.setString(6,utype);

                int i=pstmt.executeUpdate();

                if(i>0){JOptionPane.showMessageDialog(null,"Account Created.");
                    jPanelSlider1.nextPanel(9,login,jPanelSlider1.right);
                }

                else{JOptionPane.showMessageDialog(null,"Account Doesn't Created.");}

            }catch(Exception e){JOptionPane.showMessageDialog(null,e);}
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jPasswordField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyReleased
        jLabel17.setText("");
    }//GEN-LAST:event_jPasswordField2KeyReleased

    private void jPasswordField2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2MousePressed
        jPasswordField2.setText("");
    }//GEN-LAST:event_jPasswordField2MousePressed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        jLabel16.setText("");
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MousePressed
        jTextField5.setText("");
    }//GEN-LAST:event_jTextField5MousePressed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        jLabel15.setText("");      // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MousePressed
        jTextField4.setText("");
    }//GEN-LAST:event_jTextField4MousePressed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        jLabel14.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MousePressed
        jTextField3.setText("");
    }//GEN-LAST:event_jTextField3MousePressed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        jLabel14.setText("");
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MousePressed
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2MousePressed

    private void jComboBox2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MousePressed
        jLabel18.setText("");
    }//GEN-LAST:event_jComboBox2MousePressed

    private void jComboBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MousePressed
        jLabel8.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MousePressed

    private void jLabel20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseEntered

        Border border = BorderFactory.createLineBorder(Color.WHITE,2);
        jLabel20.setBorder(border);
        jLabel20.setFont(new Font("DejaVu Sans", Font.BOLD, 9));
    }//GEN-LAST:event_jLabel20MouseEntered

    private void jLabel20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseExited
        jLabel20.setBorder(null);
        jLabel20.setFont(new Font("DejaVu Sans", Font.BOLD, 11));

    }//GEN-LAST:event_jLabel20MouseExited

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked

        //jLabel13.setText("");
        jLabel14.setText("");
        jLabel15.setText("");
        jLabel16.setText("");
        jLabel17.setText("");
        jLabel18.setText("");

        jTextField4.setText("");
        jTextField5.setText("");
        jPasswordField2.setText("");
        jComboBox2.setSelectedIndex(0);

        jPanelSlider1.nextPanel(6,Signup,jPanelSlider1.left);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseExited
        jLabel19.setBorder(null);
        jLabel19.setFont(new Font("DejaVu Sans", Font.BOLD, 13));
    }//GEN-LAST:event_jLabel19MouseExited

    private void jLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseEntered
        Border border= BorderFactory.createLineBorder(Color.RED,2);
        jLabel19.setBorder(border);
        jLabel19.setFont(new Font("DejaVu Sans", Font.BOLD, 11));
    }//GEN-LAST:event_jLabel19MouseEntered

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        Connection conn=null;
        PreparedStatement pstmt=null;

        String emailids=jTextField1.getText();
        String emailhash=(gethash(emailids.getBytes(),"MD5"));
        String passs=jPasswordField1.getText();
        String passhashs=(gethash(passs.getBytes(),"MD5"));
        String utypes=(String)jComboBox1.getSelectedItem();

        if(jTextField1.getText().trim().isEmpty() && jPasswordField1.getText().trim().isEmpty()
            && utypes.equals("Select User Type"))
        {jLabel6.setText("Enter Email");
            jLabel6.setForeground(Color.red);
            jLabel7.setText("Enter Password");
            jLabel7.setForeground(Color.red);
            jLabel8.setText("Select Authority");
            jLabel8.setForeground(Color.red);}

        else
        if(jTextField1.getText().trim().isEmpty())
        {jLabel6.setText("Enter Email");
            jLabel6.setForeground(Color.red);}

        else
        if(jPasswordField1.getText().trim().isEmpty())
        {jLabel7.setText("Enter Password");
            jLabel7.setForeground(Color.red);}

        else
        if(utypes.equals("Select User Type"))
        {jLabel8.setText("Select Authority");
            jLabel8.setForeground(Color.red);}

        else{

            try{
                Class.forName("com.mysql.jdbc.Driver");
                conn=DriverManager.getConnection("jdbc:mysql:///student_management_system","root","root");
                pstmt=conn.prepareStatement("select email,pass,utype from logged_user where email=?");
                pstmt.setString(1,emailhash);
                ResultSet rs=pstmt.executeQuery();

                while(rs.next()){

                    if(emailhash.equals(rs.getString("email")) && passhashs.equals(rs.getString("pass"))
                        && utypes.equals(rs.getString("utype"))){

                        jPanelSlider1.nextPanel(1,loader,jPanelSlider1.right);
                        jLabel38.setText("<html>"+quote()+"</html>");

                        new java.util.Timer().schedule(new TimerTask() {
                            @Override
                            public void run() {

                                frames.Dashboard s = new frames.Dashboard();
                                Login_signup ls= new Login_signup();
                                s.show();
                                ls.hide();
                                dispose();
                            }
                        },1000*5);

                    }
                    else{
                        JOptionPane.showMessageDialog(null,"<html>Login Failed.<br><br>"
                            + "Please check your Email,Password And Usertype.<html>");
                    }

                }

            }catch(Exception e){JOptionPane.showMessageDialog(null,e);}
        }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        jLabel7.setText("");         // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void jPasswordField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MousePressed
        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1MousePressed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        jLabel6.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MousePressed
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MousePressed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setFont(new Font("DejaVu Sans", Font.PLAIN, 11));
        jLabel4.setForeground(Color.red);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setFont(new Font("DejaVu Sans", Font.PLAIN, 12));
        jLabel4.setForeground(Color.black);     // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        jLabel6.setText("");
        jLabel7.setText("");
        jLabel8.setText("");
        jTextField1.setText("");
        jPasswordField1.setText("");
        jComboBox1.setSelectedIndex(0);

        jPanelSlider1.nextPanel(6,forgetpass,jPanelSlider1.left);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Signup;
    private javax.swing.JPanel forgetpass;
    private javax.swing.JPanel holder;
    private javax.swing.JLabel img;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private diu.swe.habib.JPanelSlider.JPanelSlider jPanelSlider1;
    private diu.swe.habib.JPanelSlider.JPanelSlider jPanelSlider2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel6;
    private keeptoo.KGradientPanel kGradientPanel7;
    private keeptoo.KGradientPanel kGradientPanel9;
    private javax.swing.JPanel loader;
    private javax.swing.JPanel login;
    private javax.swing.JPanel root;
    // End of variables declaration//GEN-END:variables

    private Color Color(Color red) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void getLocation(int x, int y) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
